[package]
name = "password_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
clap = { version = "4.0", features = ["derive"] }
slint = "1.3"

[build-dependencies]
slint-build = "1.3"
